#include "TH1.h"
#include "TH1F.h"
#include "TFile.h"
#include "TCanvas.h"
#include "TLegend.h"
#include "TPostScript.h"
#include "TStyle.h"
#include "TLatex.h"
#include "TPaveText.h"
#include <iostream>
#include <sstream>
#include <iomanip>

using namespace std;


void compare_v2() {

  gStyle->SetOptStat(0);

  //TFile* _file0 = new TFile("file:/localdata/dsperka/CMSSW_3_8_5/src/WprimeTrigEff/WprimeMuValidation/test/WprimeTrigEff_MultiJet_148031.root","OLD");
  TFile* _file0 = new TFile("file:/localdata/dsperka/CMSSW_3_8_5/src/WprimeTrigEff/WprimeMuValidation/test/WprimeTrigEff_MultiJet_147196-148108.root","OLD");


  _file0->cd();
  TH1* reco_pt = (TH1*)demo->Get("reco_pt"); reco_pt->SetDirectory(0);
  reco_pt->Sumw2();
  TH1* reco_eta_25 = (TH1*)demo->Get("reco_eta_25"); reco_eta_25->SetDirectory(0);
  reco_eta_25->Sumw2();

  // All Eta
  TH1* l1muopen_pt = (TH1*)demo->Get("l1muopen_pt"); l1muopen_pt->SetDirectory(0);
  l1muopen_pt->Sumw2();
  TH1* l1mu3_pt = (TH1*)demo->Get("l1mu3_pt"); l1mu3_pt->SetDirectory(0);
  l1mu3_pt->Sumw2();
  TH1* l1mu5_pt = (TH1*)demo->Get("l1mu5_pt"); l1mu5_pt->SetDirectory(0);
  l1mu5_pt->Sumw2();
  TH1* l1mu7_pt = (TH1*)demo->Get("l1mu7_pt"); l1mu7_pt->SetDirectory(0);
  l1mu7_pt->Sumw2();

  TH1* l1muopen_eta_25 = (TH1*)demo->Get("l1muopen_eta_25"); l1muopen_eta_25->SetDirectory(0);
  l1muopen_eta_25->Sumw2();
  TH1* l1mu3_eta_25 = (TH1*)demo->Get("l1mu3_eta_25"); l1mu3_eta_25->SetDirectory(0);
  l1mu3_eta_25->Sumw2();
  TH1* l1mu5_eta_25 = (TH1*)demo->Get("l1mu5_eta_25"); l1mu5_eta_25->SetDirectory(0);
  l1mu5_eta_25->Sumw2();
  TH1* l1mu7_eta_25 = (TH1*)demo->Get("l1mu7_eta_25"); l1mu7_eta_25->SetDirectory(0);
  l1mu7_eta_25->Sumw2();

  TH1* hltmu3_pt = (TH1*)demo->Get("hltmu3_pt"); hltmu3_pt->SetDirectory(0);
  hltmu3_pt->Sumw2();
  TH1* hltmu5_pt = (TH1*)demo->Get("hltmu5_pt"); hltmu5_pt->SetDirectory(0);
  hltmu5_pt->Sumw2();
  TH1* hltmu7_pt = (TH1*)demo->Get("hltmu7_pt"); hltmu7_pt->SetDirectory(0);
  hltmu7_pt->Sumw2();
  TH1* hltmu9_pt = (TH1*)demo->Get("hltmu9_pt"); hltmu9_pt->SetDirectory(0);
  hltmu9_pt->Sumw2();
  TH1* hltmu11_pt = (TH1*)demo->Get("hltmu11_pt"); hltmu11_pt->SetDirectory(0);
  hltmu11_pt->Sumw2();
  TH1* hltmu13_pt = (TH1*)demo->Get("hltmu13_pt"); hltmu13_pt->SetDirectory(0);
  hltmu13_pt->Sumw2();
  TH1* hltmu15_pt = (TH1*)demo->Get("hltmu15_pt"); hltmu15_pt->SetDirectory(0);
  hltmu15_pt->Sumw2();
  TH1* hltmuFinalOR_pt = (TH1*)demo->Get("hltmuFinalOR_pt"); hltmuFinalOR_pt->SetDirectory(0);
  hltmuFinalOR_pt->Sumw2();

  TH1* hltmu3_eta_25 = (TH1*)demo->Get("hltmu3_eta_25"); hltmu3_eta_25->SetDirectory(0);
  hltmu3_eta_25->Sumw2();
  TH1* hltmu5_eta_25 = (TH1*)demo->Get("hltmu5_eta_25"); hltmu5_eta_25->SetDirectory(0);
  hltmu5_eta_25->Sumw2();
  TH1* hltmu7_eta_25 = (TH1*)demo->Get("hltmu7_eta_25"); hltmu7_eta_25->SetDirectory(0);
  hltmu7_eta_25->Sumw2();
  TH1* hltmu9_eta_25 = (TH1*)demo->Get("hltmu9_eta_25"); hltmu9_eta_25->SetDirectory(0);
  hltmu9_eta_25->Sumw2();
  TH1* hltmu11_eta_25 = (TH1*)demo->Get("hltmu11_eta_25"); hltmu11_eta_25->SetDirectory(0);
  hltmu11_eta_25->Sumw2();
  TH1* hltmu13_eta_25 = (TH1*)demo->Get("hltmu13_eta_25"); hltmu13_eta_25->SetDirectory(0);
  hltmu13_eta_25->Sumw2();
  TH1* hltmu15_eta_25 = (TH1*)demo->Get("hltmu15_eta_25"); hltmu15_eta_25->SetDirectory(0);
  hltmu15_eta_25->Sumw2();
  TH1* hltmuFinalOR_eta_25 = (TH1*)demo->Get("hltmuFinalOR_eta_25"); hltmuFinalOR_eta_25->SetDirectory(0);
  hltmuFinalOR_eta_25->Sumw2();

  //Barrel
  TH1* reco_pt_b = (TH1*)demo->Get("reco_pt_b"); reco_pt_b->SetDirectory(0);
  reco_pt_b->Sumw2();
  TH1* l1muopen_pt_b = (TH1*)demo->Get("l1muopen_pt_b"); l1muopen_pt_b->SetDirectory(0);
  l1muopen_pt_b->Sumw2();
  TH1* l1mu3_pt_b = (TH1*)demo->Get("l1mu3_pt_b"); l1mu3_pt_b->SetDirectory(0);
  l1mu3_pt_b->Sumw2();
  TH1* l1mu5_pt_b = (TH1*)demo->Get("l1mu5_pt_b"); l1mu5_pt_b->SetDirectory(0);
  l1mu5_pt_b->Sumw2();
  TH1* l1mu7_pt_b = (TH1*)demo->Get("l1mu7_pt_b"); l1mu7_pt_b->SetDirectory(0);
  l1mu7_pt_b->Sumw2();
  TH1* hltmu3_pt_b = (TH1*)demo->Get("hltmu3_pt_b"); hltmu3_pt_b->SetDirectory(0);
  hltmu3_pt_b->Sumw2();
  TH1* hltmu5_pt_b = (TH1*)demo->Get("hltmu5_pt_b"); hltmu5_pt_b->SetDirectory(0);
  hltmu5_pt_b->Sumw2();
  TH1* hltmu7_pt_b = (TH1*)demo->Get("hltmu7_pt_b"); hltmu7_pt_b->SetDirectory(0);
  hltmu7_pt_b->Sumw2();
  TH1* hltmu9_pt_b = (TH1*)demo->Get("hltmu9_pt_b"); hltmu9_pt_b->SetDirectory(0);
  hltmu9_pt_b->Sumw2();
  TH1* hltmu11_pt_b = (TH1*)demo->Get("hltmu11_pt_b"); hltmu11_pt_b->SetDirectory(0);
  hltmu11_pt_b->Sumw2();
  TH1* hltmu13_pt_b = (TH1*)demo->Get("hltmu13_pt_b"); hltmu13_pt_b->SetDirectory(0);
  hltmu13_pt_b->Sumw2();
  TH1* hltmu15_pt_b = (TH1*)demo->Get("hltmu15_pt_b"); hltmu15_pt_b->SetDirectory(0);
  hltmu15_pt_b->Sumw2();
  TH1* hltmuFinalOR_pt_b = (TH1*)demo->Get("hltmuFinalOR_pt_b"); hltmuFinalOR_pt_b->SetDirectory(0);
  hltmuFinalOR_pt_b->Sumw2();

  //Barrel
  TH1* reco_pt_e = (TH1*)demo->Get("reco_pt_e"); reco_pt_e->SetDirectory(0);
  reco_pt_e->Sumw2();
  TH1* l1muopen_pt_e = (TH1*)demo->Get("l1muopen_pt_e"); l1muopen_pt_e->SetDirectory(0);
  l1muopen_pt_e->Sumw2();
  TH1* l1mu3_pt_e = (TH1*)demo->Get("l1mu3_pt_e"); l1mu3_pt_e->SetDirectory(0);
  l1mu3_pt_e->Sumw2();
  TH1* l1mu5_pt_e = (TH1*)demo->Get("l1mu5_pt_e"); l1mu5_pt_e->SetDirectory(0);
  l1mu5_pt_e->Sumw2();
  TH1* l1mu7_pt_e = (TH1*)demo->Get("l1mu7_pt_e"); l1mu7_pt_e->SetDirectory(0);
  l1mu7_pt_e->Sumw2();
  TH1* hltmu3_pt_e = (TH1*)demo->Get("hltmu3_pt_e"); hltmu3_pt_e->SetDirectory(0);
  hltmu3_pt_e->Sumw2();
  TH1* hltmu5_pt_e = (TH1*)demo->Get("hltmu5_pt_e"); hltmu5_pt_e->SetDirectory(0);
  hltmu5_pt_e->Sumw2();
  TH1* hltmu7_pt_e = (TH1*)demo->Get("hltmu7_pt_e"); hltmu7_pt_e->SetDirectory(0);
  hltmu7_pt_e->Sumw2();
  TH1* hltmu9_pt_e = (TH1*)demo->Get("hltmu9_pt_e"); hltmu9_pt_e->SetDirectory(0);
  hltmu9_pt_e->Sumw2();
  TH1* hltmu11_pt_e = (TH1*)demo->Get("hltmu11_pt_e"); hltmu11_pt_e->SetDirectory(0);
  hltmu11_pt_e->Sumw2();
  TH1* hltmu13_pt_e = (TH1*)demo->Get("hltmu13_pt_e"); hltmu13_pt_e->SetDirectory(0);
  hltmu13_pt_e->Sumw2();
  TH1* hltmu15_pt_e = (TH1*)demo->Get("hltmu15_pt_e"); hltmu15_pt_e->SetDirectory(0);
  hltmu15_pt_e->Sumw2();
  TH1* hltmuFinalOR_pt_e = (TH1*)demo->Get("hltmuFinalOR_pt_e"); hltmuFinalOR_pt_e->SetDirectory(0);
  hltmuFinalOR_pt_e->Sumw2();
 

  // Overlap
  TH1* reco_pt_o = (TH1*)demo->Get("reco_pt_o"); reco_pt_o->SetDirectory(0);
  reco_pt_o->Sumw2();
  TH1* reco_p_o = (TH1*)demo->Get("reco_p_o"); reco_p_o->SetDirectory(0);
  reco_p_o->Sumw2();
  TH1* l1muopen_pt_o = (TH1*)demo->Get("l1muopen_pt_o"); l1muopen_pt_o->SetDirectory(0);
  l1muopen_pt_o->Sumw2();
  TH1* l1mu3_pt_o = (TH1*)demo->Get("l1mu3_pt_o"); l1mu3_pt_o->SetDirectory(0);
  l1mu3_pt_o->Sumw2();
  TH1* l1mu5_pt_o = (TH1*)demo->Get("l1mu5_pt_o"); l1mu5_pt_o->SetDirectory(0);
  l1mu5_pt_o->Sumw2();
  TH1* l1mu7_pt_o = (TH1*)demo->Get("l1mu7_pt_o"); l1mu7_pt_o->SetDirectory(0);
  l1mu7_pt_o->Sumw2();

  TH1* hltmu3_pt_o = (TH1*)demo->Get("hltmu3_pt_o"); hltmu3_pt_o->SetDirectory(0);
  hltmu3_pt_o->Sumw2();
  TH1* hltmu5_pt_o = (TH1*)demo->Get("hltmu5_pt_o"); hltmu5_pt_o->SetDirectory(0);
  hltmu5_pt_o->Sumw2();
  TH1* hltmu7_pt_o = (TH1*)demo->Get("hltmu7_pt_o"); hltmu7_pt_o->SetDirectory(0);
  hltmu7_pt_o->Sumw2();
  TH1* hltmu9_pt_o = (TH1*)demo->Get("hltmu9_pt_o"); hltmu9_pt_o->SetDirectory(0);
  hltmu9_pt_o->Sumw2();
  TH1* hltmu11_pt_o = (TH1*)demo->Get("hltmu11_pt_o"); hltmu11_pt_o->SetDirectory(0);
  hltmu11_pt_o->Sumw2();
  TH1* hltmu13_pt_o = (TH1*)demo->Get("hltmu13_pt_o"); hltmu13_pt_o->SetDirectory(0);
  hltmu13_pt_o->Sumw2();
  TH1* hltmu15_pt_o = (TH1*)demo->Get("hltmu15_pt_o"); hltmu15_pt_o->SetDirectory(0);
  hltmu15_pt_o->Sumw2();
  TH1* hltmuFinalOR_pt_o = (TH1*)demo->Get("hltmuFinalOR_pt_o"); hltmuFinalOR_pt_o->SetDirectory(0);
  hltmuFinalOR_pt_o->Sumw2();

  eff_l1muopen = new TGraphAsymmErrors;
  eff_l1muopen->BayesDivide(l1muopen_pt, reco_pt,"");
  eff_l1mu3 = new TGraphAsymmErrors;
  eff_l1mu3->BayesDivide(l1mu3_pt, reco_pt,"");
  eff_l1mu5 = new TGraphAsymmErrors;
  eff_l1mu5->BayesDivide(l1mu5_pt, reco_pt,"");
  eff_l1mu7 = new TGraphAsymmErrors;
  eff_l1mu7->BayesDivide(l1mu7_pt, reco_pt,"");
  etaeff_l1muopen = new TGraphAsymmErrors;
  etaeff_l1muopen->BayesDivide(l1muopen_eta_25, reco_eta_25,"");
  etaeff_l1mu3 = new TGraphAsymmErrors;
  etaeff_l1mu3->BayesDivide(l1mu3_eta_25, reco_eta_25,"");
  etaeff_l1mu5 = new TGraphAsymmErrors;
  etaeff_l1mu5->BayesDivide(l1mu5_eta_25, reco_eta_25,"");
  etaeff_l1mu7 = new TGraphAsymmErrors;
  etaeff_l1mu7->BayesDivide(l1mu7_eta_25, reco_eta_25,"");

  eff_l1muopen_b = new TGraphAsymmErrors;
  eff_l1muopen_b->BayesDivide(l1muopen_pt_b, reco_pt_b,"");
  eff_l1mu3_b = new TGraphAsymmErrors;
  eff_l1mu3_b->BayesDivide(l1mu3_pt_b, reco_pt_b,"");
  eff_l1mu5_b = new TGraphAsymmErrors;
  eff_l1mu5_b->BayesDivide(l1mu5_pt_b, reco_pt_b,"");
  eff_l1mu7_b = new TGraphAsymmErrors;
  eff_l1mu7_b->BayesDivide(l1mu7_pt_b, reco_pt_b,"");
 
  eff_l1muopen_o = new TGraphAsymmErrors;
  eff_l1muopen_o->BayesDivide(l1muopen_pt_o, reco_pt_o,"");
  eff_l1mu3_o = new TGraphAsymmErrors;
  eff_l1mu3_o->BayesDivide(l1mu3_pt_o, reco_pt_o,"");
  eff_l1mu5_o = new TGraphAsymmErrors;
  eff_l1mu5_o->BayesDivide(l1mu5_pt_o, reco_pt_o,"");
  eff_l1mu7_o = new TGraphAsymmErrors;
  eff_l1mu7_o->BayesDivide(l1mu7_pt_o, reco_pt_o,"");

  eff_l1muopen_e = new TGraphAsymmErrors;
  eff_l1muopen_e->BayesDivide(l1muopen_pt_e, reco_pt_e,"");
  eff_l1mu3_e = new TGraphAsymmErrors;
  eff_l1mu3_e->BayesDivide(l1mu3_pt_e, reco_pt_e,"");
  eff_l1mu5_e = new TGraphAsymmErrors;
  eff_l1mu5_e->BayesDivide(l1mu5_pt_e, reco_pt_e,"");
  eff_l1mu7_e = new TGraphAsymmErrors;
  eff_l1mu7_e->BayesDivide(l1mu7_pt_e, reco_pt_e,"");

  eff_hltmu3 = new TGraphAsymmErrors;
  eff_hltmu3->BayesDivide(hltmu3_pt, l1muopen_pt,"");
  eff_hltmu5 = new TGraphAsymmErrors;
  eff_hltmu5->BayesDivide(hltmu5_pt, l1mu3_pt,"");
  eff_hltmu7 = new TGraphAsymmErrors;
  eff_hltmu7->BayesDivide(hltmu7_pt, l1mu5_pt,"");
  eff_hltmu9 = new TGraphAsymmErrors;
  eff_hltmu9->BayesDivide(hltmu9_pt, l1mu7_pt,"");
  eff_hltmu11 = new TGraphAsymmErrors;
  eff_hltmu11->BayesDivide(hltmu11_pt, l1mu7_pt,"");
  eff_hltmu13 = new TGraphAsymmErrors;
  eff_hltmu13->BayesDivide(hltmu13_pt, l1mu7_pt,"");
  eff_hltmu15 = new TGraphAsymmErrors;
  eff_hltmu15->BayesDivide(hltmu15_pt, l1mu7_pt,"");
  eff_hltmuFinalOR = new TGraphAsymmErrors;
  eff_hltmuFinalOR->BayesDivide(hltmuFinalOR_pt, l1mu7_pt,"");

  eff_l1andhltmu11 = new TGraphAsymmErrors;
  eff_l1andhltmu11->BayesDivide(hltmu11_pt, reco_pt,"");
  eff_l1andhltmu15 = new TGraphAsymmErrors;
  eff_l1andhltmu15->BayesDivide(hltmu15_pt, reco_pt,"");


  etaeff_hltmu3 = new TGraphAsymmErrors;
  etaeff_hltmu3->BayesDivide(hltmu3_eta_25, l1muopen_eta_25,"");
  etaeff_hltmu5 = new TGraphAsymmErrors;
  etaeff_hltmu5->BayesDivide(hltmu5_eta_25, l1mu3_eta_25,"");
  etaeff_hltmu7 = new TGraphAsymmErrors;
  etaeff_hltmu7->BayesDivide(hltmu7_eta_25, l1mu5_eta_25,"");
  etaeff_hltmu9 = new TGraphAsymmErrors;
  etaeff_hltmu9->BayesDivide(hltmu9_eta_25, l1mu7_eta_25,"");
  etaeff_hltmu11 = new TGraphAsymmErrors;
  etaeff_hltmu11->BayesDivide(hltmu11_eta_25, l1mu7_eta_25,"");
  etaeff_hltmu13 = new TGraphAsymmErrors;
  etaeff_hltmu13->BayesDivide(hltmu13_eta_25, l1mu7_eta_25,"");
  etaeff_hltmu15 = new TGraphAsymmErrors;
  etaeff_hltmu15->BayesDivide(hltmu15_eta_25, l1mu7_eta_25,"");
  etaeff_hltmuFinalOR = new TGraphAsymmErrors;
  etaeff_hltmuFinalOR->BayesDivide(hltmuFinalOR_eta_25, l1mu7_eta_25,"");

  eff_hltmu3_b = new TGraphAsymmErrors;
  eff_hltmu3_b->BayesDivide(hltmu3_pt_b, l1muopen_pt_b,"");
  eff_hltmu5_b = new TGraphAsymmErrors;
  eff_hltmu5_b->BayesDivide(hltmu5_pt_b, l1mu3_pt_b,"");
  eff_hltmu7_b = new TGraphAsymmErrors;
  eff_hltmu7_b->BayesDivide(hltmu7_pt_b, l1mu5_pt_b,"");
  eff_hltmu9_b = new TGraphAsymmErrors;
  eff_hltmu9_b->BayesDivide(hltmu9_pt_b, l1mu7_pt_b,"");
  eff_hltmu11_b = new TGraphAsymmErrors;
  eff_hltmu11_b->BayesDivide(hltmu11_pt_b, l1mu7_pt_b,"");
  eff_hltmu13_b = new TGraphAsymmErrors;
  eff_hltmu13_b->BayesDivide(hltmu13_pt_b, l1mu7_pt_b,"");
  eff_hltmu15_b = new TGraphAsymmErrors;
  eff_hltmu15_b->BayesDivide(hltmu15_pt_b, l1mu7_pt_b,"");
  eff_hltmuFinalOR_b = new TGraphAsymmErrors;
  eff_hltmuFinalOR_b->BayesDivide(hltmuFinalOR_pt_b, l1mu7_pt_b,"");

  eff_hltmu3_o = new TGraphAsymmErrors;
  eff_hltmu3_o->BayesDivide(hltmu3_pt_o, l1muopen_pt_o,"");
  eff_hltmu5_o = new TGraphAsymmErrors;
  eff_hltmu5_o->BayesDivide(hltmu5_pt_o, l1mu3_pt_o,"");
  eff_hltmu7_o = new TGraphAsymmErrors;
  eff_hltmu7_o->BayesDivide(hltmu7_pt_o, l1mu5_pt_o,"");
  eff_hltmu9_o = new TGraphAsymmErrors;
  eff_hltmu9_o->BayesDivide(hltmu9_pt_o, l1mu7_pt_o,"");
  eff_hltmu11_o = new TGraphAsymmErrors;
  eff_hltmu11_o->BayesDivide(hltmu11_pt_o, l1mu7_pt_o,"");
  eff_hltmu13_o = new TGraphAsymmErrors;
  eff_hltmu13_o->BayesDivide(hltmu13_pt_o, l1mu7_pt_o,"");
  eff_hltmu15_o = new TGraphAsymmErrors;
  eff_hltmu15_o->BayesDivide(hltmu15_pt_o, l1mu7_pt_o,"");
  eff_hltmuFinalOR_o = new TGraphAsymmErrors;
  eff_hltmuFinalOR_o->BayesDivide(hltmuFinalOR_pt_o, l1mu7_pt_o,"");

  eff_hltmu3_e = new TGraphAsymmErrors;
  eff_hltmu3_e->BayesDivide(hltmu3_pt_e, l1muopen_pt_e,"");
  eff_hltmu5_e = new TGraphAsymmErrors;
  eff_hltmu5_e->BayesDivide(hltmu5_pt_e, l1mu3_pt_e,"");
  eff_hltmu7_e = new TGraphAsymmErrors;
  eff_hltmu7_e->BayesDivide(hltmu7_pt_e, l1mu5_pt_e,"");
  eff_hltmu9_e = new TGraphAsymmErrors;
  eff_hltmu9_e->BayesDivide(hltmu9_pt_e, l1mu7_pt_e,"");
  eff_hltmu11_e = new TGraphAsymmErrors;
  eff_hltmu11_e->BayesDivide(hltmu11_pt_e, l1mu7_pt_e,"");
  eff_hltmu13_e = new TGraphAsymmErrors;
  eff_hltmu13_e->BayesDivide(hltmu13_pt_e, l1mu7_pt_e,"");
  eff_hltmu15_e = new TGraphAsymmErrors;
  eff_hltmu15_e->BayesDivide(hltmu15_pt_e, l1mu7_pt_e,"");
  eff_hltmuFinalOR_e = new TGraphAsymmErrors;
  eff_hltmuFinalOR_e->BayesDivide(hltmuFinalOR_pt_e, l1mu7_pt_e,"");

  TF1 *f1 = new TF1("f1","pol0",25.0,300.0);

  TCanvas *c9 = new TCanvas("c9","c9",500,500);
  c9->Divide(2,2);
  c9->cd(1);
  eff_l1mu7->SetMarkerStyle(20);
  eff_l1mu7->SetLineColor(1);
  eff_l1mu7->SetMarkerColor(1);
  eff_l1mu7->Draw("AP");
  eff_l1mu7->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_l1mu7->GetYaxis()->SetTitle("Eff (L1|RECO)");
  eff_l1mu7->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_l1mu7,"L1SingleMu7","lp");
  legend->Draw("same");
  c9->cd(2);
  eff_l1mu7_b->SetMarkerStyle(20);
  eff_l1mu7_b->SetLineColor(1);
  eff_l1mu7_b->SetMarkerColor(1);
  eff_l1mu7_b->Draw("AP");
  eff_l1mu7_b->Fit("f1", "RME");
  eff_l1mu7_b->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_l1mu7_b->GetYaxis()->SetTitle("Eff (L1|RECO)");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<0.8");
  legend->AddEntry(eff_l1mu7_b,"L1SingleMu7","lp");
  legend->Draw("same");
  c9->cd(3);
  eff_l1mu7_o->SetMarkerStyle(20);
  eff_l1mu7_o->SetLineColor(1);
  eff_l1mu7_o->SetMarkerColor(1);
  eff_l1mu7_o->Draw("AP");
  eff_l1mu7_o->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_l1mu7_o->GetYaxis()->SetTitle("Eff (L1|RECO)");
  eff_l1mu7_o->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"0.8<|#eta|<1.2");
  legend->AddEntry(eff_l1mu7_o,"L1SingleMu7","lp");
  legend->Draw("same");
  c9->cd(4);
  eff_l1mu7_e->SetMarkerStyle(20);
  eff_l1mu7_e->SetLineColor(1);
  eff_l1mu7_e->SetMarkerColor(1);
  eff_l1mu7_e->Draw("AP");
  eff_l1mu7_e->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_l1mu7_e->GetYaxis()->SetTitle("Eff (L1|RECO)");
  eff_l1mu7_e->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"1.2<|#eta|<1.8");
  legend->AddEntry(eff_l1mu7_e,"L1SingleMu7","lp");
  legend->Draw("same");
 
  TCanvas *c16 = new TCanvas("c16","c16",600,600);
  c16->Divide(1,2);
  c16->cd(1);
  eff_l1andhltmu11->SetMarkerStyle(20);
  eff_l1andhltmu11->SetLineColor(1);
  eff_l1andhltmu11->SetMarkerColor(1);
  eff_l1andhltmu11->Draw("AP");
  eff_l1andhltmu11->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_l1andhltmu11->GetYaxis()->SetTitle("Eff (L1+HLT|RECO)");
  eff_l1andhltmu11->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_l1andhltmu11,"HLT_Mu11","lp");
  legend->Draw("same");
  c16->cd(2);
  eff_l1andhltmu15->SetMarkerStyle(20);
  eff_l1andhltmu15->SetLineColor(1);
  eff_l1andhltmu15->SetMarkerColor(1);
  eff_l1andhltmu15->Draw("AP");
  eff_l1andhltmu15->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_l1andhltmu15->GetYaxis()->SetTitle("Eff (L1+HLT|RECO)");
  eff_l1andhltmu15->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_l1andhltmu15,"HLT_Mu15","lp");
  legend->Draw("same");

  TCanvas *c10 = new TCanvas("c10","c10",500,500);
  c10->Divide(2,2);
  c10->cd(1);
  eff_hltmu11->SetMarkerStyle(20);
  eff_hltmu11->SetLineColor(1);
  eff_hltmu11->SetMarkerColor(1);
  eff_hltmu11->Draw("AP");
  eff_hltmu11->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_hltmu11,"HLT_Mu11","lp");
  legend->Draw("same");
  c10->cd(2);
  eff_hltmu11_b->SetMarkerStyle(20);
  eff_hltmu11_b->SetLineColor(1);
  eff_hltmu11_b->SetMarkerColor(1);
  eff_hltmu11_b->Draw("AP");
  eff_hltmu11_b->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11_b->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<0.8");
  legend->AddEntry(eff_hltmu11_b,"HLT_Mu11","lp");
  legend->Draw("same");
  c10->cd(3);
  eff_hltmu11_o->SetMarkerStyle(20);
  eff_hltmu11_o->SetLineColor(1);
  eff_hltmu11_o->SetMarkerColor(1);
  eff_hltmu11_o->Draw("AP");
  eff_hltmu11_o->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11_o->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11_o->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"0.8<|#eta|<1.2");
  legend->AddEntry(eff_hltmu11_o,"HLT_Mu11","lp");
  legend->Draw("same");
  c10->cd(4);
  eff_hltmu11_e->SetMarkerStyle(20);
  eff_hltmu11_e->SetLineColor(1);
  eff_hltmu11_e->SetMarkerColor(1);
  eff_hltmu11_e->Draw("AP");
  eff_hltmu11_e->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11_e->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11_e->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"1.2<|#eta|<1.8");
  legend->AddEntry(eff_hltmu11_e,"HLT_Mu11","lp");
  legend->Draw("same");

  TCanvas *c15 = new TCanvas("c15","c15",500,500);
  c15->Divide(2,2);
  c15->cd(1);
  eff_hltmu11->SetMarkerStyle(20);
  eff_hltmu11->SetLineColor(1);
  eff_hltmu11->SetMarkerColor(1);
  eff_hltmu11->Draw("AP");
  eff_hltmu11->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_hltmu11,"HLT_Mu11","lp");
  legend->Draw("same");
  c15->cd(2);
  eff_hltmu11_b->SetMarkerStyle(20);
  eff_hltmu11_b->SetLineColor(1);
  eff_hltmu11_b->SetMarkerColor(1);
  eff_hltmu11_b->Draw("AP");
  eff_hltmu11_b->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11_b->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<0.8");
  legend->AddEntry(eff_hltmu11_b,"HLT_Mu11","lp");
  legend->Draw("same");
  c15->cd(3);
  eff_hltmu11_o->SetMarkerStyle(20);
  eff_hltmu11_o->SetLineColor(1);
  eff_hltmu11_o->SetMarkerColor(1);
  eff_hltmu11_o->Draw("AP");
  eff_hltmu11_o->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11_o->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11_o->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"0.8<|#eta|<1.2");
  legend->AddEntry(eff_hltmu11_o,"HLT_Mu11","lp");
  legend->Draw("same");
  c15->cd(4);
  eff_hltmu11_e->SetMarkerStyle(20);
  eff_hltmu11_e->SetLineColor(1);
  eff_hltmu11_e->SetMarkerColor(1);
  eff_hltmu11_e->Draw("AP");
  eff_hltmu11_e->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11_e->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11_e->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"1.2<|#eta|<1.8");
  legend->AddEntry(eff_hltmu11_e,"HLT_Mu11","lp");
  legend->Draw("same");


  TCanvas *c14 = new TCanvas("c14","c14",500,500);
  c14->Divide(2,2);

  c14->cd(1);
  eff_l1mu7->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_l1mu7->GetYaxis()->SetTitle("Eff (L1|RECO)");
  eff_l1mu7->SetMarkerStyle(20);
  eff_l1mu7->SetLineColor(1);
  eff_l1mu7->SetMarkerColor(1);
  eff_l1mu7->Draw("AP");
  eff_l1mu7->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_l1mu7,"L1_SingleMu7","lp");
  legend->Draw("same");
  c14->cd(2);
  eff_hltmu11->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu11->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu11->SetMarkerStyle(20);
  eff_hltmu11->SetLineColor(1);
  eff_hltmu11->SetMarkerColor(1);
  eff_hltmu11->Draw("AP");
  eff_hltmu11->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_hltmu11,"HLT_Mu11","lp");
  legend->Draw("same");
  c14->cd(3);
  eff_hltmu13->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu13->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu13->SetMarkerStyle(20);
  eff_hltmu13->SetLineColor(1);
  eff_hltmu13->SetMarkerColor(1);
  eff_hltmu13->Draw("AP");
  eff_hltmu13->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_hltmu13,"HLT_Mu13","lp");
  legend->Draw("same");
  c14->cd(4);
  eff_hltmu15->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu15->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu15->SetMarkerStyle(20);
  eff_hltmu15->SetLineColor(1);
  eff_hltmu15->SetMarkerColor(1);
  eff_hltmu15->Draw("AP");
  eff_hltmu15->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_hltmu15,"HLT_Mu15","lp");
  legend->Draw("same");

  TCanvas *c13 = new TCanvas("c13","c13",500,500);
  c13->Divide(2,2);
  c13->cd(1);
  eff_hltmu15->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu15->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu15->SetMarkerStyle(20);
  eff_hltmu15->SetLineColor(1);
  eff_hltmu15->SetMarkerColor(1);
  eff_hltmu15->Draw("AP");
  eff_hltmu15->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<1.8");
  legend->AddEntry(eff_hltmu15,"HLT_Mu15","lp");
  legend->Draw("same");
  c13->cd(2);
  eff_hltmu15_b->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu15_b->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu15_b->SetMarkerStyle(20);
  eff_hltmu15_b->SetLineColor(1);
  eff_hltmu15_b->SetMarkerColor(1);
  eff_hltmu15_b->Draw("AP");
  eff_hltmu15_b->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"|#eta|<0.8");
  legend->AddEntry(eff_hltmu15_b,"HLT_Mu15","lp");
  legend->Draw("same");
  c13->cd(3);
  eff_hltmu15_o->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu15_o->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu15_o->SetMarkerStyle(20);
  eff_hltmu15_o->SetLineColor(1);
  eff_hltmu15_o->SetMarkerColor(1);
  eff_hltmu15_o->Draw("AP");
  eff_hltmu15_o->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"0.8<|#eta|<1.2");
  legend->AddEntry(eff_hltmu15_o,"HLT_Mu15","lp");
  legend->Draw("same");
  c13->cd(4);
  eff_hltmu15_e->GetXaxis()->SetTitle("p_{T}^{RECO} [GeV/c]");
  eff_hltmu15_e->GetYaxis()->SetTitle("Eff (HLT|L1)");
  eff_hltmu15_e->SetMarkerStyle(20);
  eff_hltmu15_e->SetLineColor(1);
  eff_hltmu15_e->SetMarkerColor(1);
  eff_hltmu15_e->Draw("AP");
  eff_hltmu15_e->Fit("f1", "RME");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"1.2<|#eta|<1.8");
  legend->AddEntry(eff_hltmu15_e,"HLT_Mu15","lp");
  legend->Draw("same");

  TCanvas *c11 = new TCanvas("c11","c11",500,500);
  c11->Divide(2,2);
  c11->cd(1);
  etaeff_l1mu7->SetMarkerStyle(20);
  etaeff_l1mu7->SetLineColor(1);
  etaeff_l1mu7->SetMarkerColor(1);
  etaeff_l1mu7->Draw("AP");
  etaeff_l1mu7->GetXaxis()->SetTitle("#eta^{RECO}");
  etaeff_l1mu7->GetYaxis()->SetTitle("Eff (L1|RECO)");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.4,"p_{T} > 25 GeV");
  legend->AddEntry(etaeff_l1mu7,"L1SingleMu7","lp");
  legend->Draw("same");
  c11->cd(2);
  etaeff_hltmu11->SetMarkerStyle(20);
  etaeff_hltmu11->SetLineColor(1);
  etaeff_hltmu11->SetMarkerColor(1);
  etaeff_hltmu11->Draw("AP");
  etaeff_hltmu11->GetXaxis()->SetTitle("#eta^{RECO}");
  etaeff_hltmu11->GetYaxis()->SetTitle("Eff (HLT|L1)");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.44,"p_{T} > 25 GeV");
  legend->AddEntry(etaeff_hltmu11,"HLT_Mu11","lp");
  legend->Draw("same");
  c11->cd(3);
  etaeff_hltmu13->SetMarkerStyle(20);
  etaeff_hltmu13->SetLineColor(1);
  etaeff_hltmu13->SetMarkerColor(1);
  etaeff_hltmu13->Draw("AP");
  etaeff_hltmu13->GetXaxis()->SetTitle("#eta^{RECO}");
  etaeff_hltmu13->GetYaxis()->SetTitle("Eff (HLT|L1)");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.44,"p_{T} > 25 GeV");
  legend->AddEntry(etaeff_hltmu13,"HLT_Mu13","lp");
  legend->Draw("same");
  c11->cd(4);
  etaeff_hltmu15->SetMarkerStyle(20);
  etaeff_hltmu15->SetLineColor(1);
  etaeff_hltmu15->SetMarkerColor(1);
  etaeff_hltmu15->Draw("AP");
  etaeff_hltmu15->GetXaxis()->SetTitle("#eta^{RECO}");
  etaeff_hltmu15->GetYaxis()->SetTitle("Eff (HLT|L1)");
  TLegend *legend = new TLegend(0.4,0.2,0.55,0.44,"p_{T} > 25 GeV");
  legend->AddEntry(etaeff_hltmu15,"HLT_Mu15","lp");
  legend->Draw("same");


}
